[project]
name = "pytorch-rnn-timeseries-bikes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "kaggle>=1.7.4.5",
    "matplotlib>=3.10.6",
    "numpy>=2.3.3",
    "pandas>=2.3.2",
    "torch>=2.8.0",
    "torchmetrics>=1.8.2",
]
